name: Lint CloudFormation Templates

on: [push]

jobs:
  lint-templates:
    name: Lint Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint Templates
        uses: ScottBrenner/cfn-lint-action@1.3.0
        with:
          args: "**/cloudformation/**/*.json"
