name: Lint CloudFormation Templates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-templates:
    name: Lint Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint Templates
        uses: ScottBrenner/cfn-lint-action@1.6.1
        with:
          args: "**/cloudformation/**/*.json"
